# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            BMTZ.nl
tagline:          'Biomedisch Technologen in de zorg'
description:      'BMTZ, de beroepsvereniging van Biomedisch Technologen in de zorg.'
url:              https://wjoachim.github.io/
baseurl:          /

author:
  name:           'Edger'
  url:            http://www.bmtz.nl

paginate:         5
excerpt_separator: <!--more-->

# Custom vars
version:          0.9.0

github:
  repo:           https://github.com/poole/hyde
