# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
# permalink:           pretty
# relative_permalinks: true

# Setup
title:               BMTZ
tagline:             'Biomedisch Technologen in de zorg'
description:         'De website van BMTZ, de beroepsvereniging van Biomedisch Technologen in de zorg! Een Biomedisch Technoloog is een professional die in het “grijze gebied” tussen het management, de zorgprofessional en de door technologie gedreven medische processen opereert.'
url:                 ''
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Edger
  url:               ''
  email:             info@bmtz.nl

# Custom vars
version:             0.9.0
