# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            BMTZ.nl
tagline:          'Biomedisch Technologen in de zorg'
description:      'BMTZ, de beroepsvereniging van Biomedisch Technologen in de zorg! Een Biomedisch Technoloog is een professional die in het "grijze gebied" tussen het management, de zorgprofessional en de door technologie gedreven medische processen opereert.'
url:              https://wjoachim.github.io/
baseurl:          /

author:
  name:           'Edger'
  url:            http://www.bmtz.nl

paginate:         5

# Custom vars
version:          0.9.0

github:
  repo:           https://github.com/poole/hyde
